name: Add comment on PR

on: [pull_request]

PR-comment:
      if: github.actor != 'user1' && github.actor != 'user2' && github.actor != 'user3'
      runs-on: ubuntu-latest
      steps:
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: Have you followed the [contributions guidance](<url_to_contribution_guidance>)? Content PRs should generally be made against the the [source repo](https://github.com/<owner>/<repo>).'
            })